general:
  output: "text"  # "text" or "json"
  parallelism: 1  # Number of concurrent tests

tests:
  - name: "Google Echo Test"
    dest: "8.8.8.8"
    request_type: "echo" # "echo" or "timestamp"
    expected_result: "response" # "response" or "timeout"
    timeout: "2s"
